Repository redhat-developer/kam, pull requests merged in 2020-10, with the labels that each got.

#47 Fix typos in docs
  docs/commands/README.md
  docs/journey/day1/README.md
  docs/journey/day1/prerequisites/argocd.md
  pkg/cmd/kam.go
Labels: approved, lgtm

#50 fix typos in docs and command
  docs/commands/README.md
  pkg/cmd/kam.go
Labels: approved, kind/bug, lgtm

#48 Remove duplicate entry from root owners file
  OWNERS
Labels: approved, kind/cleanup, lgtm

#49 Test container cleanup
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/cleanup, lgtm

#51 Organize the Getting Started
  README.md
Labels: approved, lgtm

#52 Final round of doc updates
  README.md
  docs/journey/day2/README.md
  docs/journey/day2/img/argocd-refresh.png
Labels: approved, kind/cleanup, lgtm

#53 Updating labels in pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/cleanup, lgtm

#55 Doc PR for KAM Day1 and Day2
  docs/journey/day1/README.md
  docs/journey/day2/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test

#57 fix typos in journey 1 docs
  docs/journey/day1/README.md
Labels: approved, kind/documentation, lgtm, needs-ok-to-test

#56 kam service add creates a new config directory.
  docs/journey/day2/README.md
  pkg/pipelines/environment_test.go
  pkg/pipelines/ioutils/file_utils.go
  pkg/pipelines/service.go
  pkg/pipelines/service_test.go
Labels: approved, lgtm

#58 [docs]Update devconsole section in the docs
  docs/devconsole/README.md
  docs/devconsole/img/GitOps_Applications.jpg
  docs/devconsole/img/GitOps_Dashboard.jpg
  docs/devconsole/img/GitOps_Installation.jpg
  docs/devconsole/img/GitOps_Operator.jpg
  docs/devconsole/img/GitOps_Service.jpg
  docs/devconsole/setup-gitops.md
Labels: approved, lgtm

#59 Installing github cli in test container
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/enhancement, lgtm

#60 Update devconsole docs
  docs/devconsole/README.md
Labels: approved, lgtm

#61 Generate markdown
  .github/workflows/ci-build.yml
  .gitignore
  Makefile
  docs/commands/README.md
  docs/commands/bootstrap/README.md
  docs/commands/environment/README.md
  docs/commands/kam.md
  docs/commands/kam_bootstrap.md
  docs/commands/kam_build.md
  docs/commands/kam_environment.md
  docs/commands/kam_environment_add.md
  docs/commands/kam_service.md
  docs/commands/kam_service_add.md
  docs/commands/kam_version.md
  docs/commands/kam_webhook.md
  docs/commands/kam_webhook_create.md
  docs/commands/kam_webhook_delete.md
  docs/commands/kam_webhook_list.md
  docs/commands/version/README.md
  docs/commands/webhook/README.md
  go.sum
  pkg/cmd/kam.go
  tools/cmd-docs/main.go
Labels: approved, kind/documentation, lgtm

#66 fix typo
  pkg/cmd/bootstrap.go
Labels: approved, kind/bug, lgtm

#54 Preparing test cluster and installing operators
  Makefile
  docs/test/ci-guide.md
  docs/test/test-guide.md
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/prepare-test-cluster.sh
  scripts/setup-operators.sh
Labels: approved, kind/enhancement, lgtm

#67 Fixing doc generate failure
  Makefile
  docs/commands/kam_service.md
  docs/commands/kam_service_add.md
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/enhancement, kind/failing-test, lgtm

#70 Remove unnecessary make target
  Makefile
Labels: approved, kind/cleanup, lgtm

#69 output built binaries in "dist" folder
  .github/workflows/release.yml
  .gitignore
  Makefile
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/enhancement, lgtm

#71 Adding argocd install script that can be referenced from other E2E tests
  scripts/install-argocd.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/enhancement, lgtm

#68 Create developer login session in CI
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/enhancement, lgtm

#75 Push repo to GitHub
  docs/commands/kam_bootstrap.md
  docs/journey/day1/README.md
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/cmd/ui/ui.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/environment_test.go
  pkg/pipelines/secrets/secrets_test.go
  pkg/pipelines/utils.go
  pkg/pipelines/utils_test.go
  pkg/pipelines/yaml/resources_test.go
  test/error.go
Labels: approved, lgtm

#76 Fix issue with error message validation.
  pkg/pipelines/yaml/resources_test.go
Labels: approved, kind/bug, lgtm

#78 Adding Docker CLI install script
  scripts/install-docker-cli.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/enhancement, lgtm
