Repository redhat-developer/kam, pull requests merged in 2020-12, with the labels that each got.

#105 Change the name of the keyring save command-line argument.
  docs/commands/kam_bootstrap.md
  go.mod
  pkg/cmd/bootstrap.go
Labels: approved, kind/cleanup, lgtm

#108 Add default ref to namespaces.
  pkg/pipelines/namespaces/namespaces.go
  pkg/pipelines/namespaces/namespaces_test.go
Labels: approved, lgtm

#112 Clarify that overwrite only overwrites the local filesystem.
  docs/commands/kam_bootstrap.md
  pkg/cmd/bootstrap.go
Labels: approved, kind/documentation, lgtm

#115 Create ssh directory path
  openshift-ci/build-root/Dockerfile
Labels: kind/enhancement, lgtm

#113 Trailing slash correction during bootstrap service add.
  pkg/cmd/utility/utility.go
  pkg/cmd/utility/utility_test.go
Labels: approved, lgtm

#116 fix: Prompting for hostname for internal image registry(GITOPS-419)
  docs/commands/kam_bootstrap.md
  docs/commands/kam_service.md
  docs/commands/kam_service_add.md
  pkg/cmd/bootstrap.go
  pkg/cmd/service/add.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/imagerepo/imagerepo.go
  pkg/pipelines/imagerepo/imagerepo_test.go
  pkg/pipelines/service.go
Labels: approved, lgtm

#125 Increase sealed-secrets installation timeout
  scripts/setup-operators.sh
Labels: kind/failing-test
