Repository redhat-developer/kam, pull requests merged in 2020-11, with the labels that each got.

#79 Openshift pipelines 1.2
  go.mod
  go.sum
  pkg/pipelines/eventlisteners/eventlisteners_test.go
  pkg/pipelines/scm/github_test.go
  pkg/pipelines/scm/gitlab_test.go
  pkg/pipelines/scm/utility.go
  pkg/pipelines/scm/utility_test.go
Labels: approved, kind/cleanup, lgtm

#81 Add go mod status message in openshift CI
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/enhancement, lgtm

#84 Fix typo in commandline
  README.md
Labels: approved, kind/documentation, lgtm

#80 Allow kam commands to reuse Git auth-token
  docs/commands/kam_bootstrap.md
  docs/commands/kam_webhook_create.md
  docs/commands/kam_webhook_delete.md
  docs/commands/kam_webhook_list.md
  docs/journey/day1/README.md
  docs/journey/day2/README.md
  go.mod
  go.sum
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/cmd/ui/ui.go
  pkg/cmd/ui/validate.go
  pkg/cmd/webhook/create_test.go
  pkg/cmd/webhook/delete_test.go
  pkg/cmd/webhook/list_test.go
  pkg/cmd/webhook/webhook_cmd.go
  pkg/pipelines/accesstoken/accesstoken.go
  pkg/pipelines/accesstoken/accesstoken_test.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/webhook/webhook.go
Labels: approved, lgtm

#89 Install sudo in test container
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/enhancement, lgtm

#92 Add note about argocd permissions.
  docs/FAQ/GitopsFAQ.md
Labels: approved, kind/documentation, lgtm

#90 Break link app env
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/argocd/argocd_test.go
  pkg/pipelines/environments/environments.go
  pkg/pipelines/environments/environments_test.go
  pkg/pipelines/service_test.go
Labels: approved, kind/cleanup, lgtm

#95 Correct documentation w.r.t gitops repo creation.
  docs/journey/day1/README.md
  docs/journey/day1/prerequisites/gitops_repo.md
Labels: approved, lgtm

#91 Export GitHub token
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/enhancement, lgtm

#97 Restrict adding files to just the generated ones.
  pkg/pipelines/utils.go
  pkg/pipelines/utils_test.go
Labels: approved, kind/bug, lgtm

#99 Change long description
  docs/commands/kam.md
  pkg/cmd/kam.go
Labels: approved, kind/cleanup, lgtm, ok-to-test

#93 Generated argocd application to use overlays folder instead of base
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/argocd/argocd_test.go
Labels: approved, lgtm, ok-to-test

#98 Fix image param
  pkg/pipelines/pipelines/pipelines.go
  pkg/pipelines/pipelines/pipelines_test.go
  pkg/pipelines/triggers/pipelinerun.go
  pkg/pipelines/triggers/pipelinerun_test.go
  pkg/pipelines/triggers/templates.go
  pkg/pipelines/triggers/templates_test.go
Labels: approved, kind/bug, lgtm
