Repository redhat-developer/kam, pull requests merged in 2021-03, with the labels that each got.

#126 Update bootstrap command in Day1 journey Doc
  docs/journey/day1/README.md
Labels: approved, kind/bug

#183 Update OWNERS
  OWNERS
Labels: approved, lgtm

#175 Make Argo CD admin in environments managed by kam
  docs/journey/day1/README.md
  docs/journey/day1/prerequisites/argocd.md
  docs/journey/day1/prerequisites/gitops_operator.md
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/environments/environments.go
  pkg/pipelines/environments/environments_test.go
  pkg/pipelines/roles/service_rolebinding.go
  pkg/pipelines/service_test.go
Labels: approved, lgtm

#184 Executing kam bootstrap command
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
  scripts/prepare-test-cluster.sh
  test/e2e/features/basic.feature
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/enhancement, lgtm

#186 Precise version check
  test/e2e/features/basic.feature
Labels: approved, kind/enhancement, lgtm, ok-to-test

#187 fixed panic for invalid gitops/service repo URL
  pkg/cmd/ui/ui.go
  pkg/cmd/ui/validate.go
  pkg/cmd/ui/validate_test.go
Labels: approved, lgtm

#190 Updated docs for 4.7
  README.md
  docs/FAQ/GitopsFAQ.md
  docs/README.md
  docs/devconsole/README.md
  docs/devconsole/img/GitOps_Applications.jpg
  docs/devconsole/img/GitOps_Dashboard.jpg
  docs/devconsole/img/GitOps_Installation.jpg
  docs/devconsole/img/GitOps_Operator.jpg
  docs/devconsole/img/GitOps_Service.jpg
  docs/journey/day1/README.md
  docs/journey/day1/img/ArgoCD_ConsoleSecrets.png
  docs/journey/day1/img/ArgoCD_CopyPassword.png
  docs/journey/day1/img/ArgoCD_Link.png
  docs/journey/day1/img/ArgoCD_Login.png
  docs/journey/day1/img/ArgoCD_Pods.png
  docs/journey/day1/img/Argocd_operator_gitops.png
  docs/journey/day1/prerequisites/argocd.md
  docs/journey/day1/prerequisites/img/argocd-1.png
  docs/journey/day1/prerequisites/img/argocd-2.png
  docs/journey/day1/prerequisites/img/argocd-3.png
  docs/journey/day1/prerequisites/img/argocd-4.png
  docs/journey/day1/prerequisites/img/ss-1.png
  docs/journey/day1/prerequisites/img/ss-3.png
  docs/journey/day1/prerequisites/img/ss-6.png
  docs/journey/day1/prerequisites/img/ss-7.png
  docs/journey/day1/prerequisites/img/tekton-1.png
  docs/journey/day1/prerequisites/img/tekton-2.png
  docs/journey/day1/prerequisites/img/tekton-3.png
  docs/journey/day1/prerequisites/img/tekton-4.png
  docs/journey/day1/prerequisites/pipelines_operator.md
  docs/journey/day1/prerequisites/sealed_secrets.md
  docs/journey/day2/README.md
  docs/model/README.md
Labels: approved, kind/documentation, lgtm

#122 Onboarding test doc
  Makefile
  docs/test/ci-guide.md
  docs/test/test-guide.md
  test/e2e/features/basic.feature
  test/e2e/features/manual.feature
  test/e2e/kamsuite/dirops.go
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/documentation, lgtm

#192 Updating quay prereq doc
  docs/journey/day1/prerequisites/quay.md
Labels: approved, kind/documentation, lgtm, ok-to-test

#185 KAM to function without security manager
  docs/commands/kam_bootstrap.md
  docs/commands/kam_service.md
  docs/commands/kam_service_add.md
  docs/journey/day1/README.md
  docs/journey/day2/README.md
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/cmd/service/add.go
  pkg/cmd/ui/ui.go
  pkg/cmd/utility/utility.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/secrets/secrets.go
  pkg/pipelines/service.go
  pkg/pipelines/service_test.go
Labels: approved, kind/enhancement

#191 fix: Update trigger binding to use the new extensions field
  pkg/pipelines/scm/github.go
  pkg/pipelines/scm/github_test.go
  pkg/pipelines/scm/gitlab.go
  pkg/pipelines/scm/gitlab_test.go
Labels: approved, lgtm, ok-to-test

#195 Template for running specific local tests
  Makefile
  docs/test/test-guide.md
  test/e2e/features/local.feature
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/enhancement, lgtm

#194 fix: add defaults for image repo and pipelines
  pkg/pipelines/service.go
  pkg/pipelines/service_test.go
Labels: approved, lgtm

#198 Git action CI failure debug
  .github/workflows/ci-build.yml
  go.sum
Labels: approved, kind/failing-ci, lgtm

#196 Make local tag global
  test/e2e/features/local.feature
Labels: approved, kind/enhancement, lgtm, ok-to-test

#199 Remove unnecessary call from OpenShift CI unit test job
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/cleanup, lgtm

#200 Remove unnecessary call from OpenShift CI e2e test job
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/cleanup, lgtm

#201 Remove unnecessary CI variables
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/cleanup, lgtm

#202 Update Day 1 operations for Sealed Secrets
  docs/journey/day1/README.md
Labels: approved, lgtm

#203 Disable --commit-status-tracker by default
  docs/commands/kam_bootstrap.md
  pkg/cmd/bootstrap.go
Labels: approved, lgtm

#208 Update new image registry path
  openshift-ci/build-root/Dockerfile
Labels: kind/failing-ci

#206 [GITOPS-750] Hide Commit Status Tracker
  docs/commands/kam_bootstrap.md
  pkg/cmd/bootstrap.go
  pkg/pipelines/triggers/pipelinerun.go
  pkg/pipelines/triggers/pipelinerun_test.go
  pkg/pipelines/triggers/templates.go
  pkg/pipelines/triggers/templates_test.go
Labels: approved, lgtm

#211 Update owners file
  OWNERS
Labels: kind/cleanup

#205 Rename OpenShift GitOps default Argo CD instance name in KAM
  docs/journey/day1/README.md
  pkg/pipelines/argocd/argocd.go
  scripts/setup-operators.sh
Labels: approved, lgtm

#215 Update pictures in day 1 guide to match new Argo CD instance name
  docs/journey/day1/img/ArgoCD_ConsoleSecrets.png
  docs/journey/day1/img/ArgoCD_CopyPassword.png
Labels: approved, lgtm

#213 Update default ref in the annotation URL
  pkg/pipelines/namespaces/namespaces.go
  pkg/pipelines/namespaces/namespaces_test.go
Labels: approved, lgtm

#216 Update argocd login flow in docs
  docs/journey/day1/README.md
  docs/journey/day1/img/ArgoCD_ConsoleSecrets.png
  docs/journey/day1/img/ArgoCD_CopyPassword.png
Labels: approved, kind/documentation, lgtm

#214 Adding kubectl binary in openshift CI test container
  scripts/install-kubectl.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/enhancement, lgtm

#210 Enable gitlab local test
  docs/test/test-guide.md
  test/e2e/features/basic.feature
  test/e2e/features/local.feature
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/enhancement, lgtm

#218 The description for the kam service --git-repo-url option is wrong (829)
  docs/commands/kam_service.md
  docs/commands/kam_service_add.md
  pkg/cmd/service/add.go
Labels: approved, kind/bug, lgtm

#217 Locking argocd cli version
  scripts/install-argocd.sh
Labels: approved, kind/enhancement, lgtm
