Repository redhat-developer/kam, pull requests merged in 2021-02, with the labels that each got.

#159 [563] Smart defaults - update docs
  docs/journey/day1/README.md
Labels: approved, kind/documentation, lgtm

#161 Update argocd namespace to openshift-gitops
  docs/FAQ/GitopsFAQ.md
  docs/devconsole/README.md
  docs/journey/day1/README.md
  docs/journey/day1/prerequisites/gitops_operator.md
  docs/journey/day1/prerequisites/img/argocd-instance.png
  docs/journey/day1/prerequisites/img/gitops-installation.png
  docs/journey/day1/prerequisites/img/gitops-listing.png
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/argocd/argocd_test.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/service_test.go
Labels: approved, lgtm

#163 docs: Fix some typos, punctuation and phrasing
  docs/journey/day1/README.md
  docs/journey/day2/README.md
Labels: approved, lgtm

#160 [142] kam should trim leading and trailing spaces from input
  pkg/cmd/ui/ui.go
Labels: kind/bug

#165 Switch to the new TriggerTemplate param naming.
  pkg/pipelines/triggers/pipelinerun.go
  pkg/pipelines/triggers/pipelinerun_test.go
Labels: approved, kind/bug, lgtm

#168 Fix requirements section
  docs/journey/day1/README.md
Labels: approved, lgtm

#167 Improve support for GitLab project repos.
  pkg/pipelines/git/repository.go
  pkg/pipelines/git/repository_test.go
Labels: approved, kind/bug, lgtm

#170 Address issue with multiple namespace files being created.
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/imagerepo/imagerepo.go
Labels: approved, kind/bug, lgtm

#172 Fix sealed secret instance name typo
  scripts/setup-operators.sh
Labels: kind/bug

#171 Install GitOps operator
  scripts/prepare-test-cluster.sh
  scripts/setup-operators.sh
Labels: approved, kind/enhancement, lgtm

#174 Remove duplicates when adding to the Kustomization representation.
  pkg/pipelines/bootstrap.go
  pkg/pipelines/resources/kustomization.go
  pkg/pipelines/resources/kustomization_test.go
Labels: approved, lgtm

#177 Fix GitLab access token documentation.
  docs/journey/day1/img/gl_access_token_3.png
  docs/journey/day1/prerequisites/gitlab_access_token_steps.md
Labels: approved, kind/bug, lgtm
