Repository redhat-developer/kam, pull requests merged in 2021-07, with the labels that each got.

#257 Fix CI repo delete race condition
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/bug, kind/failing-test, lgtm

#258 Update pipelines csv search string
  scripts/setup-operators.sh
Labels: approved, kind/bug, lgtm

#255 Guidance how generated secrets can be stored as SealedSecrets (#943)
  docs/journey/day1/README.md
  docs/journey/day1/prerequisites/img/ss-1.png
  docs/journey/day1/prerequisites/img/ss-2.png
  docs/journey/day1/prerequisites/img/ss-3.png
  docs/journey/day1/prerequisites/img/ss-4.png
  docs/journey/day1/prerequisites/img/ss-5.png
  docs/journey/day1/prerequisites/img/ss-6.png
  docs/journey/day1/prerequisites/img/ss-7.png
  docs/journey/day1/prerequisites/img/ss-8.png
  docs/journey/day1/prerequisites/sealed_secrets.md
  pkg/cmd/bootstrap.go
  pkg/cmd/service/add.go
Labels: approved, kind/enhancement, lgtm

#259 Create basic auth secret for private repository
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/secrets/secrets.go
Labels: approved, lgtm

#261 Disable commit status task for enterprise repository
  pkg/pipelines/bootstrap.go
  pkg/pipelines/pipelines/pipelines.go
  pkg/pipelines/pipelines/pipelines_test.go
Labels: approved, lgtm

#260 The add service command introduces backslashes in kustomize.yaml (#1212)
  pkg/pipelines/environments/environments.go
  pkg/pipelines/environments/environments_test.go
Labels: approved, kind/bug, lgtm
