Repository redhat-developer/kam, pull requests merged in 2021-08, with the labels that each got.

#263 Improve Add Service documentation regarding unencrypted secrets (#262)
  docs/journey/day2/README.md
Labels: kind/documentation, lgtm, approved

#264 Update FAQ note for enterprise repo
  docs/FAQ/GitopsFAQ.md
Labels: lgtm, approved

#265 Create an application/service in the new environment and push configu…
  test/e2e/features/basic.feature
Labels: kind/enhancement, lgtm, approved

#270 Add blog link that speaks about how kam cli works
  README.md
Labels: lgtm, approved, needs-ok-to-test

#272 Updating kam day1 doc
  docs/journey/day1/README.md
Labels: lgtm, approved
