Repository redhat-developer/kam, pull requests merged in 2021-05, with the labels that each got.

#234 Temporary docker container1.16
  openshift-ci/build-root/Dockerfile.temp
Labels: kind/failing-test

#235 Updating bootstrap environment up doc
  docs/journey/day1/README.md
Labels: approved, kind/documentation, lgtm

#225 Bringing the bootstrapped environment up
  scripts/openshiftci-presubmit-all-tests.sh
  test/e2e/features/basic.feature
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/enhancement, lgtm

#239 Update operator subscription channel
  scripts/setup-operators.sh
Labels: approved, kind/enhancement, kind/failing-test, lgtm

#241 Openshift CI docker file clean up
  openshift-ci/build-root/Dockerfile
  openshift-ci/build-root/Dockerfile.temp
Labels: approved, kind/cleanup, lgtm

#242 doc: Update prerequisite: pipelines operator is no longer installed by gitops operator
  docs/journey/day1/README.md
  docs/journey/day1/prerequisites/gitops_operator.md
  docs/journey/day1/prerequisites/img/pipelines-installation.png
  docs/journey/day1/prerequisites/img/pipelines-listing.png
  docs/journey/day1/prerequisites/pipelines_operator.md
Labels: kind/documentation, lgtm

#244 Install pipeline operator
  scripts/setup-operators.sh
Labels: approved, kind/enhancement, kind/failing-test, lgtm

#248 Fix warning message when pipelines operator is not found
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
Labels: approved, lgtm

#237 Bringing the deployment infrastructure up
  test/e2e/features/basic.feature
  test/e2e/kamsuite/kamsuite.go
Labels: approved, kind/enhancement, lgtm

#245 Improve error message if the git driver flag is not specified (#987)
  pkg/cmd/bootstrap.go
  pkg/cmd/ui/validate.go
  pkg/cmd/ui/validate_test.go
Labels: approved, kind/bug, lgtm

#247 Use port name instead of number
  pkg/pipelines/eventlisteners/routes.go
  pkg/pipelines/eventlisteners/routes_test.go
  pkg/pipelines/routes/routes.go
  pkg/pipelines/routes/routes_test.go
Labels: approved, lgtm

#236 Add finally task to set commit status
  docs/FAQ/GitopsFAQ.md
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/cmd/ui/ui.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/pipelines/pipelines.go
  pkg/pipelines/pipelines/pipelines_test.go
  pkg/pipelines/statustracker/deployment.go
  pkg/pipelines/statustracker/deployment_test.go
  pkg/pipelines/tasks/set_commit_status_task.go
  pkg/pipelines/triggers/pipelinerun.go
  pkg/pipelines/triggers/pipelinerun_test.go
  pkg/pipelines/triggers/templates.go
  pkg/pipelines/triggers/templates_test.go
Labels: approved, lgtm

#240 KAM on windows uses backslash in paths (844)
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/argocd/argocd_test.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/config/config_test.go
  pkg/pipelines/config/parser.go
  pkg/pipelines/config/validate.go
  pkg/pipelines/dryrun/dryrun_test.go
  pkg/pipelines/environment_test.go
  pkg/pipelines/environments/environments.go
  pkg/pipelines/imagerepo/imagerepo.go
  pkg/pipelines/service.go
  pkg/pipelines/service_test.go
  pkg/pipelines/tekton_builder.go
  pkg/pipelines/tekton_builder_test.go
  pkg/pipelines/yaml/resources_test.go
Labels: approved, kind/bug, lgtm

#251 Validate manifest yamls
  docs/journey/day1/README.md
Labels: approved, kind/bug, kind/documentation, lgtm
