Repository redhat-developer/kam, pull requests merged in 2021-04, with the labels that each got.

#221 fixed the error message for push-to-git if repo exists
  pkg/pipelines/utils.go
Labels: approved, kind/bug, lgtm

#219 Insecure option is not available in interactive mode (812)
  pkg/cmd/bootstrap.go
  pkg/cmd/ui/ui.go
Labels: approved, lgtm

#223 Update ArgoCD Service Account name
  pkg/pipelines/argocd/argocd.go
Labels: approved, kind/bug, lgtm

#222 bug: delete existing .git directory if push-to-git and overwrite are set
  pkg/cmd/bootstrap.go
  pkg/cmd/ui/ui.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/utils.go
  pkg/pipelines/utils_test.go
Labels: approved, kind/bug, lgtm

#232 Build root clean up
  openshift-ci/build-root/Dockerfile
  openshift-ci/build-root/Dockerfile.exporthome
  openshift-ci/build-root/Dockerfile.unprivileged
Labels: kind/cleanup, kind/failing-test
