Repository redhat-developer/kam, pull requests merged in 2021-01, with the labels that each got.

#131 Enhance docu, how to configure private git repos. Fix #130
  docs/journey/day1/README.md
Labels: kind/documentation, ok-to-test

#110 Add app labels to applications
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/argocd/argocd_test.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/environments/environments.go
  pkg/pipelines/environments/environments_test.go
  pkg/pipelines/resources/kustomization.go
  pkg/pipelines/service_test.go
Labels: approved, lgtm

#141 Improve the documentation for the service-add command.
  docs/commands/kam_service.md
  docs/commands/kam_service_add.md
  pkg/cmd/service/add.go
Labels: kind/documentation, lgtm

#143 Improve duplicate repo url error.
  pkg/pipelines/config/validate.go
  pkg/pipelines/config/validate_test.go
Labels: kind/enhancement

#146 Add completion command.
  docs/commands/kam.md
  docs/commands/kam_completion.md
  pkg/cmd/completion.go
  pkg/cmd/kam.go
Labels: approved, kind/enhancement, lgtm

#139 Add a dockerfile to create an image to serve kam binary
  Dockerfile.serve
Labels: approved, lgtm

#155 Inconsistent case in Yes/No (yes/no) type of options in bootstrap cmd
  pkg/cmd/ui/ui.go
Labels: approved, kind/bug, lgtm

#129 Improve sealedsecret namespace
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
Labels: approved, kind/enhancement, ok-to-test

#153 Add note on building
  README.md
Labels: kind/documentation, lgtm

#107 Don't fail when adding a service to an environment with no pipelines.
  pkg/pipelines/service.go
  pkg/pipelines/service_test.go
Labels: approved, lgtm

#158 Smart default for bootstrap options except for epic point 5; Fix 147
  docs/commands/kam_bootstrap.md
  pkg/cmd/bootstrap.go
  pkg/cmd/bootstrap_test.go
  pkg/cmd/ui/ui.go
  pkg/cmd/ui/validate.go
  pkg/pipelines/bootstrap.go
Labels: approved, kind/bug, kind/enhancement, lgtm
