Repository redhat-developer/kam, pull requests merged in 2021-09, with the labels that each got.

#269 gitops-1169: Interactive mode with default option doesn't support push to git
  pkg/cmd/ui/ui.go
Labels: lgtm, approved

#273 Scenarios for applying secrets and creating webhook
  test/e2e/features/basic.feature
Labels: lgtm, approved

#276 Updating owners file
  OWNERS
Labels: lgtm, approved

#268 updated README with devconsole 4.9 changes
  docs/devconsole/README.md
  docs/devconsole/img/GitOps_4.8_Environments.png
  docs/devconsole/img/GitOps_4.8_Environments_Tooltip.png
  docs/devconsole/img/GitOps_4.9_Environments.png
  docs/devconsole/img/GitOps_App_Details.png
  docs/devconsole/img/GitOps_Applications.jpg
  docs/devconsole/img/GitOps_Dashboard.jpg
  docs/devconsole/img/GitOps_Service.jpg
  docs/devconsole/img/GitOps_Service.png
Labels: lgtm, approved

#275 GITOPS-1000 Parse the image only if git repository is provided
  pkg/pipelines/service.go
  pkg/pipelines/service_test.go
Labels: lgtm, approved

#277 Adding more scenarios for day1 operation
  test/e2e/features/basic.feature
  test/e2e/kamsuite/dirops.go
  test/e2e/kamsuite/kamsuite.go
Labels: kind/enhancement, lgtm, approved, kind/code-refactoring

#278 Update secrets section in the docs
  docs/journey/day1/README.md
Labels: kind/documentation, lgtm, approved

#279 Use managed-by label to manage environments
  docs/journey/day1/README.md
  pkg/pipelines/argocd/argocd.go
  pkg/pipelines/bootstrap.go
  pkg/pipelines/bootstrap_test.go
  pkg/pipelines/environments/environments.go
  pkg/pipelines/environments/environments_test.go
  pkg/pipelines/namespaces/namespaces.go
  pkg/pipelines/namespaces/namespaces_test.go
  pkg/pipelines/service_test.go
Labels: kind/enhancement, lgtm, approved

#282 Scenario for adding webhook(day2)
  test/e2e/features/basic.feature
  test/e2e/kamsuite/kamsuite.go
Labels: kind/enhancement, lgtm, approved
