Repository redhat-developer/kam, pull requests merged in 2022-04, with the labels that each got.

#303 add examples to command descriptions
  docs/commands/kam_bootstrap.md
  docs/commands/kam_environment_add.md
  docs/commands/kam_service_add.md
  docs/commands/kam_webhook_create.md
  docs/commands/kam_webhook_delete.md
  pkg/cmd/bootstrap.go
  pkg/cmd/environment/add.go
  pkg/cmd/service/add.go
  pkg/cmd/webhook/create.go
  pkg/cmd/webhook/delete.go
Labels: lgtm, approved

#302 Adds support for ppc64le and s390x
  Makefile
Labels: kind/enhancement, lgtm, approved, ok-to-test

#305 Create different GitOps repositories for different OCP versions in CI checks
  test/e2e/kamsuite/kamsuite.go
Labels: lgtm, approved

#308 Generate checksums for kam binaries
  .github/workflows/release.yml
  Dockerfile.serve
  Makefile
  config/index.html
  scripts/generate-checksum.sh
Labels: kind/enhancement, lgtm, approved

#309 Use tail cmd to extract file extension
  scripts/generate-checksum.sh
Labels: lgtm, approved

#310 Build for linux/ppc64le and linux/s390x
  Makefile
Labels: kind/enhancement, lgtm, approved, ok-to-test

#311 Release linux/ppc64le and linux/s390x binaries
  .github/workflows/release.yml
Labels: kind/enhancement, lgtm, approved, ok-to-test

#312 Serve linux/ppc64le and linux/s390x binaries
  Dockerfile.serve
  config/index.html
  scripts/openshiftci-presubmit-unittests.sh
Labels: kind/enhancement, lgtm, approved, ok-to-test
